---
- name: "Deploy Cron script from template: {{ item.template }}"
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 755
    owner: root
    group: root
  loop: "{{ cronjobs }}"

- name: "Set up cronjob for {{ item.name }} ({{ item.frequency }})"
  cron:
    name: "{{ item.name }}"
    special_time: "{{ item.frequency }}"
    job: "{{ item.job }}"
  loop: "{{ cronjobs }}"
  when: item.frequency is defined

- name: "Deploy job: {{ item.name }}"
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.job }}"
  loop: "{{ fixed_time_cronjobs }}"

