- set_fact: 
    package_name: prbz-overview

- include_tasks: tasks/deploy-webapp.yml

- name: "Checks prbz-overview configuration - Aphrodite"
  template: 
    src: templates/prbz-overview.aphrodite.properties.json.j2 
    dest: /home/jboss/prbz-overview/aphrodite.properties.json 
    owner: jboss 
    group: jboss 
    mode: "0644"

